name: simple_live_tv_app
description: A new Flutter project.
publish_to: "none"
version: 1.6.5+10605

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_live_core:
    path: ../simple_live_core
  cupertino_icons: ^1.0.2
  remixicon: ^1.0.0 #Remix鍥炬爣

  # 妗嗘灦銆佸伐鍏?
  get: ^4.7.2 #鐘舵€佺鐞嗐€佽矾鐢辩鐞嗐€佸浗闄呭寲
  dio: ^5.9.0 #缃戠粶璇锋眰
  hive: 2.2.3 #鎸佷箙鍖栧瓨鍌?
  hive_flutter: 1.1.0 #鎸佷箙鍖栧瓨鍌?
  logger: 2.6.2 #鏃ュ織
  intl: ^0.20.2 #鍥介檯鍖?
  flutter_screenutil: ^5.9.3 #UI閫傞厤
  uuid: ^4.5.1 #UUID
  signalr_netcore: ^1.4.4 #SignalR
  crypto: ^3.0.6

  #Widget
  flutter_staggered_grid_view: ^0.7.0 #鐎戝竷娴?GridView
  flutter_easyrefresh: 2.2.2 #涓嬫媺鍒锋柊銆佷笂鎷夊姞杞?
  extended_image: ^9.1.0 #鎷撳睍Image,鏀寔缂撳瓨
  flutter_smart_dialog: ^4.9.8+9 #鍚勭寮圭獥 Toast/Dialog/Popup
  lottie: ^3.1.3 #Lottie鍔ㄧ敾
  qr_flutter: ^4.1.0 #浜岀淮鐮?
  sticky_headers: ^0.3.0+2 #鍚搁《
  canvas_danmaku: ^0.2.7 #寮瑰箷

  #绯荤粺浜や簰
  package_info_plus: ^8.0.0 #鍖呬俊鎭?
  url_launcher: 6.2.5 #鎵撳紑閾炬帴
  network_info_plus: ^4.1.0+1
  udp: ^5.0.3 #UDP
  device_info_plus: ^9.1.2 #璁惧淇℃伅
  wakelock_plus: ^1.2.11 #灞忓箷甯镐寒锛宮edia_kit涓嚜甯︼紝浣嗕技涔庝笉鐢熸晥

  # 瑙嗛鎾斁
  media_kit: 1.1.11
  media_kit_video: 1.2.5
  media_kit_libs_video: 1.0.5

dependency_overrides:
  fading_edge_scrollview: ^4.1.1
  collection: ^1.19.1
  media_kit_libs_android_video: 1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/statement.txt
    - assets/images/
    - assets/icons/
    - assets/lotties/
